[package]
name = "renderdoc"
version = "0.2.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "RenderDoc application bindings for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ebkalderon/renderdoc-rs"
documentation = "https://docs.rs/renderdoc/"
readme = "README.md"
keywords = ["graphics", "profile", "renderdoc", "trace"]

[features]
default = ["app", "replay", "glutin"]
app = ["renderdoc_sys/app"]
replay = ["renderdoc_sys/replay"]

[dependencies]
bitflags = "~1.0"
glutin = { version = "~0.12", optional = true }
lazy_static = "0.2.8"
renderdoc_sys = { version = "0.1", path = "renderdoc_sys" }
shared_library = "0.1.8"

[target.'cfg(windows)'.dependencies]
winapi = "~0.2.8"
wio = "~0.1.2"

[dev-dependencies]
gfx = "~0.17"
gfx_window_glutin = "~0.20"
glutin = "~0.12"

[workspace]
members = ["renderdoc_sys"]
