[package]
name = "renderdoc"
version = "0.2.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "RenderDoc application bindings for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ebkalderon/renderdoc-rs"
documentation = "https://docs.rs/renderdoc/"
readme = "README.md"
keywords = ["graphics", "profile", "renderdoc", "trace"]

[features]
default = ["glutin"]

[dependencies]
bitflags = "~1.0"
lazy_static = "0.2.8"
shared_library = "0.1.8"

glutin = { version = "~0.12", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "~0.2.8"
wio = "~0.1.2"

[dev-dependencies]
gfx = "0.16.2"
gfx_window_glutin = "0.19"
glutin = "~0.12"

[workspace]
members = ["renderdoc_sys"]
