[package]
name = "renderdoc"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "RenderDoc application bindings for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ebkalderon/renderdoc.rs"
documentation = ""
readme = "README.md"
keywords = ["graphics", "profile", "renderdoc", "trace"]

[dependencies]
bitflags = "1.0"
lazy_static = "0.2.8"
shared_library = "0.1.7"

winit = { version = "0.8", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"

[dev-dependencies]
gfx = "0.16.1"
gfx_window_glutin = "0.18"
glutin = "0.10"
